"use client";

import * as React from "react";
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";

const privacyContent = `
<h2>Privacy Policy</h2>
<p>Last updated: ${new Date().toLocaleDateString()}</p>

<h3>Data Collection</h3>
<p>We collect only the minimum data necessary to provide our database exploration service. We do not sell or share your personal data with third parties.</p>

<h3>Data Storage</h3>
<p>Your database connection credentials are stored locally in your browser's localStorage. We never transmit your database credentials to our servers.</p>

<h3>AI Processing</h3>
<p>When you use AI-powered features, your database schema and query results may be sent to AI providers (Google Gemini) to generate natural language explanations. This data is used solely for generating responses and is not stored permanently.</p>

<h3>Cookies</h3>
<p>We use essential cookies to maintain your session state and preferences. No tracking or advertising cookies are used.</p>

<h3>Your Rights</h3>
<p>You have the right to:</p>
<ul>
  <li>Request deletion of your data</li>
  <li>Opt out of AI features</li>
  <li>Export your data</li>
</ul>

<h3>Contact</h3>
<p>If you have questions about this privacy policy, please contact us through the GitHub repository.</p>
`;

const termsContent = `
<h2>Terms of Service</h2>
<p>Last updated: ${new Date().toLocaleDateString()}</p>

<h3>Acceptance of Terms</h3>
<p>By using oh-my-database, you agree to these terms. If you do not agree to these terms, please do not use this application.</p>

<h3>Use of Service</h3>
<p>oh-my-database is provided as a tool to help non-technical users explore and understand their own database data. You agree to use this service only for lawful purposes.</p>

<h3>Data Responsibility</h3>
<p>You are responsible for:</p>
<ul>
  <li>Ensuring you have the right to access any database you connect to</li>
  <li>Backing up your data before making changes</li>
  <li>Understanding the queries generated by AI before executing them</li>
</ul>

<h3>Disclaimer</h3>
<p>This software is provided "as is" without warranty of any kind. We are not responsible for any data loss or damage resulting from the use of this application.</p>

<h3>Limitation of Liability</h3>
<p>In no event shall the developers of oh-my-database be liable for any damages arising from the use or inability to use this software.</p>

<h3>Changes to Terms</h3>
<p>We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
`;

interface PrivacyDialogProps {
  children: React.ReactNode;
}

function PrivacyDialog({ children }: PrivacyDialogProps) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Privacy Policy</DialogTitle>
          <DialogDescription>
            How we handle your data and protect your privacy
          </DialogDescription>
        </DialogHeader>
        <div 
          className="prose prose-sm max-w-none text-muted-foreground"
          dangerouslySetInnerHTML={{ __html: privacyContent }}
        />
      </DialogContent>
    </Dialog>
  );
}

interface TermsDialogProps {
  children: React.ReactNode;
}

function TermsDialog({ children }: TermsDialogProps) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Terms of Service</DialogTitle>
          <DialogDescription>
            Terms and conditions for using oh-my-database
          </DialogDescription>
        </DialogHeader>
        <div 
          className="prose prose-sm max-w-none text-muted-foreground"
          dangerouslySetInnerHTML={{ __html: termsContent }}
        />
      </DialogContent>
    </Dialog>
  );
}

export { PrivacyDialog, TermsDialog };
